name=F1 26 UDP Telemetry Parser
version=0.0.1
author=MacManley
maintainer=dar2q
sentence=UDP Telemetry Parser for the F1 26 Game
paragraph=UDP Telemetry Parser for the F1 26 Game
category=Communication
depends=WiFiUDP
url=https://github.com/dar2q/f1-26-udp
architectures=*